name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug you encountered
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Open Playa
        2. Load sequence...
        3. Click on...
        4. See error
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust version
      description: Output of `rustc --version`
      placeholder: "rustc 1.75.0 (82e1608df 2023-12-21)"
    validations:
      required: true

  - type: input
    id: playa-version
    attributes:
      label: Playa version
      description: Version number or commit hash
      placeholder: "0.1.23 or git commit hash"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 11
        - Windows 10
        - Ubuntu 22.04
        - Ubuntu 20.04
        - Other Linux
        - macOS 14 Sonoma
        - macOS 13 Ventura
        - macOS 12 Monterey
        - Other macOS
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy and paste any relevant log output (set RUST_LOG=debug for verbose logs)
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, image sequence details, or any other relevant information
